---
#Deployment API
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperatura-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temperatura-web
  template:
    metadata:
      labels:
        app: temperatura-web
    spec:
      containers:
        - name: temperatura-web
          image: na1jefferson/conversao-temperatura:v1
          ports:
            - containerPort: 8080
---
# Service do temperatura-web
apiVersion: v1
kind: Service
metadata:
  name: temperatura-web
spec:
  selector:
    app: temperatura-web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  type: LoadBalancer